CREATE TABLE students ( email VARCHAR(225) PRIMARY KEY, name VARCHAR(255), rollno INTEGER, place VARCHAR(255), password VARCHAR(255) );
CREATE TABLE books ( bookId INTEGER PRIMARY KEY AUTO_INCREMENT, bookName VARCHAR(255), author VARCHAR(255), price INTEGER, quantity INTEGER );
CREATE TABLE sales ( saleId INTEGER PRIMARY KEY AUTO_INCREMENT, bookId INTEGER, user VARCHAR(255));